### ISSUE TITLE
Rank Post Styling extension compatibility

### ISSUE THREAD

**Issue by Galixte** [BoardTools/QuickReply#34]
Hi @lavigor @PayBas,

if i post a message with QuickReply Reloaded, then i can’t use the dropdown menu when i click on username in mini-profile from the second message or the third message of topic (this seems to be random): https://github.com/PayBas/RankPostStyling.

Maybe PayBas has to read this: https://github.com/Tatiana5/QuickReply/wiki#how-to-make-this-extension-compatible-with-other-extensions & https://github.com/Tatiana5/QuickReply/wiki#developers-guide.

Or maybe it's a bug in QuickReply Reloaded extension.

**Comment by lavigor** [comment]
I think it is because both of the extensions QuickReply and Rank Post Styling use the same events `viewtopic_body_postrow_post_after` and `viewtopic_body_postrow_post_before`.
But I don't know whether it is currently possible to resolve such conflicts.
Maybe @PayBas can suggest a solution.

**Comment by Galixte** [comment]
Hi @lavigor,

yes he can, but since the april month i haven’t seen any activity about him on GitHub and phpBB.com.

If you could test to resolve it, please.

**Comment by lavigor** [comment]
The only way for now is by doing custom edits.
Maybe I can create a MODX file for that, but the edits are quite simple.

Assuming that both QuickReply Reloaded and Rank Post Styling extensions are installed on the board.

### NOTES
1. Posts will be styled only in prosilver-based styles (unless you apply the edits below to other styles).
2. Posts will be styled only when QuickReply Reloaded extension is enabled, no matter whether quick reply is enabled or disabled in a certain forum.
3. You will need to apply the changes below after each update of QuickReply Reloaded (edits 1 and 2) or Rank Post Styling (edit 3) extension.

The edits 1 and 2 may be included in one of the following releases of QuickReply Reloaded so that you will not need to apply them again.

### CHANGES

1) OPEN `ext/boardtools/quickreply/styles/prosilver/template/event/viewtopic_body_postrow_post_before.html`.

FIND
```
<!-- ENDIF -->
```
ADD AFTER
```
<div class="post-container<!-- IF postrow.RANK_STYLE --> {postrow.RANK_STYLE}<!-- ENDIF -->">
```

2) OPEN `ext/boardtools/quickreply/styles/prosilver/template/event/viewtopic_body_postrow_post_after.html`

FIND
```
<!-- IF postrow.S_LAST_ROW and not S_QUICKREPLY_REQUEST -->
```
ADD BEFORE
```
</div><!-- /.post-container -->
```

3) REMOVE `ext/paybas/rankpoststyling/styles/all/template/event/viewtopic_body_postrow_post_before.html` AND `ext/paybas/rankpoststyling/styles/all/template/event/viewtopic_body_postrow_post_after.html`

**Comment by Galixte** [comment]
Thanks you so much @lavigor !

**Comment by Galixte** [comment]
Hi @Sajaki,

do you think you can insert a solution about this problem, since your continue the development of Rank Post Styling extension ?
