### ISSUE TITLE
Migrate: Using standard method

### ISSUE THREAD

**Issue by Galixte** [BoardTools/QuickReply#42]
In step 3, i can see: “Copy all files from this repository to ext/tatiana5/quickreply. This step will save your data so that they will not be deleted on the fifth step.”.

Why the link of archive is: https://github.com/Tatiana5/QuickReply/archive/migrate.zip instead of this: https://github.com/BoardTools/QuickReply/archive/migrate.zip ?

The archive from this link: https://github.com/Tatiana5/QuickReply/archive/migrate.zip contains all files from QuickReply Reloaded (old repository) that i have already and currently on my FTP.

Why i should upload the last files on my FTP from the old repository to save data ? I don’t understand why in step 5: “Click "Delete data" button” will save data, in my opinion it will delete those.

**Comment by lavigor** [comment]
@Galixte, please do not be hurry.
I haven't posted the explanations on phpbb.com yet. ;D

Link are the same just because old links are redirected automatically. I wanted to fix them later.

The actions are needed to delete old migrations (as you can see it is the only directory in the migrate package) without affecting user data.

Please note, that the special migrate package is NOT the same as the old repository, it should replace the old files in old vendor directory.

**Comment by Galixte** [comment]
Yes i will wait, i want to help you. I haven’t do anything for migration, only read your README ;)
