### ISSUE TITLE
Cannot find module quickreply_qn_module.php

### ISSUE THREAD

**Issue by ravand1990** [BoardTools/QuickReply#58]
Hi there!

phpbb version: 3.1.9
Theme: ComBoot 3.1 dev

Whenever i try to enable your QuickReply plugin i cannot access the Extensions page anymore and i get the following error message:

```
Cannot find module ./../includes/acp/\boardtools\quickreply\acp\quickreply_qn_module.php

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/includes/functions_module.php
LINE: 571
CALL: trigger_error()

FILE: [ROOT]/adm/index.php
LINE: 81
CALL: p_master->load_active()
```
I have tried all of your branches but all of them give me this error.
I have found some versions on the forums where i don't get this error message, however most of the features aren't working on those

Am i missing something?

Thanks in advance!

**Comment by lavigor** [comment]
Hello, @ravand1990.

The only version that is compatible with ComBoot is currently 1.1.0 that is now in its alpha stage and is in active development (`develop` branch).

Please answer the following questions.

How did you install the extension?
Did you update from a previous version?

The above error could possibly occur when the extension was not updated properly.
Try disabling it, removing its data and installing again.

Also please follow the updates, the first beta version will be released soon.

**Comment by ravand1990** [comment]
Hey @lavigor thanks for your quick reply,

I tried the develop branch and that one didn't work for me :/
I tried installing with the "Upload Extensions" Extension and also manually, i made sure to delete all files and remainings from the previously tested versions and i also didn't use QuickReply earlier before, actually this is my first and clean phpBB installation.

Any other ideas?
Thansk in advance and looking forward to the beta version :) keep up the good work

**Comment by lavigor** [comment]
@ravand1990, glad to hear that the installation problem is resolved.

> The QuickReply container appears if i select "Standard" in the "Quick reply form type" with the other settings it isn't present.

If you select the `Fixed` type, the form itself should be stuck to the bottom of the page containing a text field `Type your reply here...`. This is a new look of quick reply form.
The `Fixed with post reloads` type is work-in-progress and at the moment is identical to the `Fixed` type.

> Also the form is closed by default, is this intended?

Yes, in `Standard` type this is intended because quick reply form is hidden by default in ComBoot style. I just did it because it was like that in the style.

`Fixed` form style is one of the new major features of the next release, it makes replies even quicker and also contains fullscreen mode.

**Comment by ravand1990** [comment]
@lavigor thanks for your the information

Also what about the ajax features? Do they work in this alpha version? None of them seem to work for me

Thanks in advance

**Comment by lavigor** [comment]
@ravand1990, all existing features work for me.
Ajax features, including Ajax pagination and Ajax posting, are tested in several browsers in several styles (ComBoot, prosilver and some other prosilver-based styles).
ComBoot is the only supported non-prosilver-based style at the moment. 😉

**Comment by ravand1990** [comment]
@lavigor i checked again wether "fixed" shows anything, but unfortunately nothing, i see a quick form flashing in and out when i refresh the page, but other than that nothing remains from the QuickReply form

Also the ajax features like highlighting a text to quote don't work either :/

**Comment by lavigor** [comment]
@ravand1990, the fixed form should look like that in ComBoot:
![quickreply_compact](https://cloud.githubusercontent.com/assets/7805635/16548049/9da42f28-4192-11e6-9edb-e6c5911e3a4f.png)

The quick quote dropdown is shown here:
![quickreply_quick_quote](https://cloud.githubusercontent.com/assets/7805635/16548047/954c9f7c-4192-11e6-8441-6dd0a68cbe86.png)

Do you really have a *clean* phpBB installation?
Could you please give me a test account so that I can check the problem on your board?

**Comment by ravand1990** [comment]
@lavigor sure feel free to register on the page, no activation needed: https://forum.ravand.org/ucp.php?mode=register

**Comment by Tatiana5** [comment]
@ravand1990, `ComBoot-3.1-master` is not `ComBoot`
Delete the style in Administration panel, rename folder `ComBoot-3.1-master` to `ComBoot`, install style again

**Comment by ravand1990** [comment]
@Tatiana5 wow... that really did the trick... :S thanks a bunch man. Is this normal or a bug? Might consider hinting at this somewhere or fixing it if it is a bug

**Comment by lavigor** [comment]
@ravand1990, there's just a lack of installation instructions.
It should be mentioned that the name of the directory should be edited to be the same as the name of the style - `ComBoot`.

@TheZoker that probably needs mentioning anywhere. 😉

**Comment by TheZoker** [comment]
@lavigor I think of a good solution for this :)

**Comment by ravand1990** [comment]
Glad i could help with my issue :)
